# Generated by Django 5.2 on 2025-09-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0003_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='selectcategory',
            field=models.CharField(choices=[('working', 'Working'), ('installing', 'Installing'), ('servicing', 'Servicing')], default='working', max_length=50),
        ),
    ]
