# Generated by Django 5.2 on 2025-09-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0004_contactinfo_selectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVElectrical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageurl', models.URLField()),
            ],
        ),
    ]
