# Generated by Django 5.2 on 2025-09-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0005_cctvelectrical'),
    ]

    operations = [
        migrations.CreateModel(
            name='datasave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('mail', 'Male'), ('female', 'Female'), ('other', 'Other')], default='select gender', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_otp', models.CharField(blank=True, default='000000', max_length=6)),
                ('confirmpassword', models.CharField(max_length=50)),
                ('session_otp', models.CharField(blank=True, default='000000', max_length=6)),
            ],
        ),
    ]
