# Generated by Django 5.2 on 2025-09-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0006_datasave'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasave',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='datasave',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='select gender', max_length=50),
        ),
    ]
