# Generated by Django 5.2 on 2025-09-18 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0009_delete_imageupload_datasave_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
